"""add_is_preview_hidden

Revision ID: ff59e5879b0b
Revises: fix_blob_name_001
Create Date: 2025-11-29 14:22:42.902812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff59e5879b0b'
down_revision: Union[str, None] = 'fix_blob_name_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_preview_hidden', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_preview_hidden')
    # ### end Alembic commands ###


